-   id: polars_upgrade
    name: polars_upgrade
    description: Automatically upgrade syntax for newer versions.
    entry: polars_upgrade
    language: python
    types: [python]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
